config/routes.rb
Rails.application.routes.draw do
	root :to => "entries#form"
  devise_for :users,
  controllers:
  { 
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmation: 'users/confirmation',
    unlocks: 'users/unlocks',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'

  }

  get 'not_authorized' => 'entries#not_authorized'
  resources :users do
    resources :groups do
      member do
      post 'add_member'
    end
      resources :entries
    end
  end
  resources :entries do
    member do
      post 'calculation'
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
	belongs_to :user
	has_many :entries
	has_many :members
	accepts_nested_attributes_for :entries
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    @groups = current_user.groups
  end

  def show
  end

  def new
    @group = Group.new
    @users = User.all
  end

  def edit
    @users = User.all
  end

  def create
    @group = current_user.groups.new group_params

    respond_to do |format|
      if @group.save
        format.html { redirect_to user_groups_path(current_user), flash: { success: 'Group Created Successfully'}}
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|

      if @group.update(group_params)
        format.html { redirect_to user_groups_path(current_user), notice: 'Group was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to user_groups_path(current_user), notice: 'Group was successfully destroyed.' }
    end
  end

  def add_member
    

  end

  private

  def set_group
    @group = current_user.groups.find_by(id: params[:id])
    # redirect_to not_authorized and return if @group.blank?
  end

  def group_params
    params.require(:group).permit(:group, :description)
  end   
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for [current_user, group] do |form| %>
<div class="limiter">
    <div class="container-login100">
      <div class="wrap-login100 p-t-85 p-b-20">
  <div class="wrap-input100 validate-input m-t-85 m-b-35">
   </br></br></br>
   <div class="input100">
    <span class="focus-input100" data-placeholder="Title"></span>
    <br />
    <%= form.text_field :group,rows: 2, placeholder: "Enter Title of expence"%>

   </div>
  </div>
  <div class="wrap-input100 validate-input m-t-85 m-b-35">
   </br></br></br>
   <div class="input100">
    <span class="focus-input100" data-placeholder="Description"></span>
    <br />
    <%= form.text_field :description, rows: 1, class: "form-control", placeholder: "Enter Description"%>
   </div>
  </div>
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-12">
    <br>
    <div class="form-group">
      <% if params[:action ] == "new" %>
  <label class="col-md-4 control-label" for="Member">Add Members into Group by Email</label>
  <% else %>
  <label class="col-md-4 control-label" for="Member">Edit Members into Group by Email</label>
  <% end %>
  <div class="col-md-4">
    
    <select id="Member" name="Member" class="form-control">
      <% @users.each do |f| %>
      <option><%=f.username%></option>
      <% end %>
    </select>
  </div>


<%= select_tag 'members[]', options_for_select(User.all.map{ |s| [s.email]})%>


</div>
    <%= form.submit class: 'btn btn-primary btn-large' %>
   </div>
  </div>
<% end %>




















    

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Cancel', user_groups_path(current_user) %>

app/views/groups/form.html.erb
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-t-85 p-b-20">
				<form class="login100-form validate-form">

					<span class="login100-form-title p-b-70">
						Welcome Sabeen janu
					</span>
					
						<%=image_tag("DP.jpg",class: "img")%>
			</div>
		</div>
	</div>

app/views/groups/index.html.erb
<div class="center">
<h1>Groups</h1>
<div class="container">
<div class="row">
<div class="col-md-4"></div>
<div class="col-md-4">


<table class="table">
    <thead class="thead-dark">
      <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Discription</th>
      <th></th>

      <th scope="col">Action</th>
      </tr>
      <% @groups.each_with_index do |group, index| %>
        </thead>
        <tbody>
        <tr>
          <th scope="row"><%= index+1 %></th>
          <td><%=link_to group.group,user_group_path(current_user, group) %></td>
          <td><%= group.description %></td>
          <td></td>
          <td><%= link_to 'Edit', edit_user_group_path(current_user, group),class: "btn btn-l btn-primary" %></td>
          <td><%= link_to 'Destroy',user_group_path(current_user, group), method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-l btn-danger" %></td>
        </tr>

      <% end %>
      
  </tbody>
</table>
<br>
  </div>
  </div>
</div>

<%= link_to 'New',new_user_group_path(current_user),class: "btn btn-l btn-success" %>
</div>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', user_groups_path(current_user) %>

app/views/groups/show.html.erb
<div class="center">
  <p><strong class="">Expence Title: <%= @group.group %></strong></p>
  <p><strong>Expence: </strong><%= @group.description %></p>
  <button>All Entries</button>
  <div class="container">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <table class="table">
         <thead class="thead-dark">
           <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th></th>
            <th scope="col">Action</th>
          </tr>
          <% @group.entries.each do |entry| %>

        </thead>
        <tbody>
          <tr>
            <th scope="row"><%=entry.id %></th>
            <td><%= link_to entry.name,user_group_entry_path(entry.user,entry.group,entry)%></td>
            <td><%= entry.price %></td>
            <td></td>
            <td><%= link_to 'Edit', edit_user_group_entry_path(entry.user,entry.group,entry),class: "btn btn-l btn-primary" %></td>
            
            <td><%= link_to 'Destroy', user_group_entry_path(entry.user,entry.group,entry), method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-l btn-danger" %></td>
            <%end%>
          </tr>
        </tbody>
      </table>
      
    </div>
  </div>
</div>



<h1>Grand Total: <%= sum_of_prices(@group) %> </h1><br>
<%= link_to 'Join Members', edit_user_group_path(current_user, @group),class: "btn btn-l btn-info" %> |
<%= link_to 'Edit Group', edit_user_group_path(current_user, @group),class: "btn btn-l btn-primary" %> |

<%= link_to 'New Entry', new_user_group_entry_path(current_user,@group) ,class: "btn btn-l btn-success"%>  |

<%= link_to 'Back', user_groups_path(current_user) ,class: "btn btn-l btn-danger"%>
</div>

</div>