config/routes.rb
Rails.application.routes.draw do
	root :to => "entries#form"
  devise_for :users,
  controllers:
  { 
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmation: 'users/confirmation',
    unlocks: 'users/unlocks',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'

  }

  get 'not_authorized' => 'entries#not_authorized'
  resources :users do
    resources :groups do
      member do
      post 'add_member'
    end
      resources :entries
    end
  end
  resources :entries do
    member do
      post 'calculation'
    end
  end
end

app/views/shared/_flash.html.erb
<% unless flash.empty? %>
     <script type="text/javascript">
       <% flash.each do |f| %>
         <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'success') %>
          toastr['<%= type %>']('<%= f[1] %>');

       <% end %>
     </script>
  <% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Split Divider", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user  %>
        <li><%= link_to "Home",user_groups_path(current_user)%></li>
        <li><%= link_to "New Group",new_user_group_path(current_user) %></li>
        <li><%#= link_to "New Entry",new_entry_path(current_user) %></li>
        <li><%= link_to "Profile update",edit_user_registration_path %></li>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
        <% if !current_user  %>
        
        <li><%= link_to "Sign Up",new_user_registration_path ,class: "glyphicon glyphicon-user"%></li>
        
        <li><%= link_to "Login User",user_session_path,class: "glyphicon glyphicon-user" %></li>
        <% else %>
          <li><%= link_to "Logout User",destroy_user_session_path, :method => :delete ,class: "glyphicon glyphicon-log-out" %>
        <% end %>
        </ul>
        
          
        </li>
      </ul>
    </div>
  </div>
</nav>